config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  get 'home/about'
  root 'friends#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
  @friend = current_user.friends.find_by(id: params[:id])
  redirect_to friends_path, notice: "Not authorized to edit this friend" if @friend.nil?
  end

  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    
    <%= form.text_field :first_name, class: "form-control", placeholder: "Name of your friend" %>
  </div>

  <div class="field mb-3"">
    
    <%= form.text_field :last_name, class: "form-control", placeholder: "Last name of your friend" %>
  </div>

  <div class="field mb-3"">
    
    <%= form.text_field :email, class: "form-control", placeholder: "His or her email!" %>
  </div>

  <div class="field mb-3"">
    
    <%= form.text_field :phone, class: "form-control", placeholder: "Does he or she have a phone?" %>
  </div>

  <div class="field mb-3">
    
    <%= form.text_field :twitter, class: "form-control", placeholder: "Twitter account maybe?"  %>
  </div>

  <div class="field mb-3">
    
    <%= form.number_field :user_id, id: :friend_user_id, class: "form-control", value: current_user.id, type: "hidden" %>
  </div>


</br>
  <div class="actions">
    <%= form.submit class: "btn btn-outline-dark" %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>
</br>
<%= link_to 'Back', friends_path, class: "btn btn-secondary btn-sm"%> 
<%= link_to 'Show', @friend, class: "btn btn-info btn-sm" %> 
<%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>

app/views/friends/index.html.erb
<% if user_signed_in?%>
<h1>Friend List</h1>


<table class="table table-hover table-striped table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th colspan=""></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <% if friend.user == current_user %>
      <tr>
        <td>
            <%= link_to friend.first_name + ' ' + friend.last_name, friend %> 
        </td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>

        <td><%= link_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
      </tr>
      <% end %>
      


    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path, class: "btn btn-outline-secondary" %>
<% else %>
<h1>Home world!</h1>
      This is my first Rails Webpage...
        PROBANDO VISUAL STUDIO
  <% end %>

app/views/friends/new.html.erb
<h1>New Friend</h1>
</br>
<%= render 'form', friend: @friend, class: "btn btn-outline-dark" %>
</br>
<%= link_to 'Back', friends_path, class: "btn btn-outline-dark" %>

app/views/friends/show.html.erb
<div class="card text-center">
  <div class="card-header">
    Friend
  </div>
  <div class="card-body">
    <h1 class="card-title"><%= @friend.first_name %> <%= @friend.last_name %></h1><br>
    <p class="card-text">Email: <%= @friend.email %></p>
    <p class="card-text">Phone: <%= @friend.phone %></p>
    
    <a href="#" class="btn btn-primary"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
  <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
</svg> <%= @friend.twitter %></a>
  </div>
  <div class="card-footer text-muted">

  <%= link_to 'Edit', edit_friend_path(@friend), class: "btn btn-outline-dark" %> 
<%= link_to 'Back', friends_path, class: "btn btn-outline-dark" %>
  <%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friends App', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About Us", home_about_path, class: "nav-link"%>
        </li>

        
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "New Friend", new_friend_path, class: "nav-link"%>
          </li>
       
          <li class="nav-item">
            <%= link_to "Edit profile", edit_user_registration_path, class: "nav-link"%>
          </li>          
          
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link"%>
          </li>

          


        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up",  new_user_registration_path, class: "nav-link"%>
          </li>

          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link"%>
          </li>
        <% end %>
        

        
        
        
      </ul>
      
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>
This is my first Rails Webpage...
PROBANDO VISUAL STUDIO

app/views/home/index.html.erb
<h1>Home world!</h1>
This is my first Rails Webpage...
PROBANDO VISUAL STUDIO

app/views/layouts/_alerts.html.erb
<div class="alert alert-dark" role="alert">
  <%= notice %><a href="#" class="alert-link">X</a>.
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Friends App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render 'home/header'%>
    <div class = "container">
    </br>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>

    <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>